### PR TITLE
Add POCO C++ Libraries

### PR DESCRIPTION
**Pull request by murahtin**

### CODE REVIEW

**Comment by murahtin** [comment]
Compiling tested on all platforms.

**Comment by alllexx88** [comment]
Thank you for your contribution!

However, there're some minor issues that I see.

First, the staging command: instead of

```
$(POCO_BUILD_DIR)/.staged: $(POCO_BUILD_DIR)/.built
	rm -f $@
	$(MAKE) -C $(@D) DESTDIR=$(STAGING_DIR) install
	touch $@
```

it should be

```
$(POCO_BUILD_DIR)/.staged: $(POCO_BUILD_DIR)/.built
	rm -f $@
	$(MAKE) -C $(@D) DESTDIR=$(STAGING_PREFIX) install
	touch $@
```

since you configured it without prefix.

Second, you should properly pass Optware-ng linking flags: it should be `echo 'SHAREDOPT_LINK  = $(STAGING_LDFLAGS) $(POCO_LDFLAGS)'`, instead of echo 'SHAREDOPT_LINK  = -Wl,-rpath,$$(LIBPATH)/ss', and in case it installs some dependency libs to `$(TARGET_PREFIX)/lib/ss`, then also set `POCO_LDFLAGS=-Wl,-rpath,$(TARGET_PREFIX)/lib/ss` (on line 57).

Similarly with compilation flags: please add `$(STAGING_CPPFLAGS) $(POCO_CPPFLAGS)` (or `$(TARGET_CFLAGS)` instead of `$(STAGING_CPPFLAGS)` if you're absolutely sure you won't need anything previously staged) to the cflags.

Also, please change the commit message (github supports forced pushs, so just create a new pull request when done) to follow this template:

```
poco: initial addition
<description>
```

I should mention this somewhere in the wikis :smile:

**Comment by murahtin** [comment]
Thank you for the recommendation. I do not know much English, I write through a translator, so I apologize for any errors. This is my first attempt to participate in a free project, GitHub and use the first time.
The ultimate goal of participation in your project is the development of a transparent proxy server blocking advertisements on the lists of AdBlock, running on the router. The project uses a library ROSO. Using privoxy for this purpose did not suit me. I am Russian, and we have a saying - "if you want to do well, do it yourself."

And now, in order:

    $(POCO_BUILD_DIR)/.staged: $(POCO_BUILD_DIR)/.built
        rm -f $@
        $(MAKE) -C $(@D) DESTDIR=$(STAGING_DIR) install
        touch $@

it was determined by the pattern, I do not change it.

Regarding flags - I try to fix it. But there were problems ...

Once again, thanks for the clarification.

**Comment by murahtin** [comment]
Changes applied.

**Comment by alllexx88** [comment]
The Makefile looks good to me now, except that you don't really need to manually add `-Wl,-rpath,$(TARGET_PREFIX)/lib` to `POCO_LDFLAGS`: it's part of `STAGING_LDFLAGS`. You only need similar flags for libs not in `$(TARGET_PREFIX)/lib` (which I thought was maybe the case, judging from the `SHAREDOPT_LINK  = -Wl,-rpath,$$(LIBPATH)/ss` line). The only thing that's a bit messy is the commit messages: please make soft reset of last two commits locally (`git reset --soft HEAD~2`: see http://stackoverflow.com/questions/927358/how-to-undo-last-commits-in-git), then commit the change with proper commit message (the one from your second commit), and force push it to github (`git push -f`). Finally, create a new pull request with your new commit.

To clarify things a bit more, the staging command in template uses `DESTDIR=$(STAGING_DIR)`, because it configures the source with `$(TARGET_PREFIX)` prefix, while you configured `poco` with no prefix, so you have to use `DESTDIR=$(STAGING_DIR)$(TARGET_PREFIX)`, which is the same as `DESTDIR=$(STAGING_PREFIX)`. Notice, btw, how you changed the make install invocation in packaging target to `DESTDIR=$(POCO_IPK_DIR)$(TARGET_PREFIX)` from `DESTDIR=$(POCO_IPK_DIR)`: you had to do this for the same reason -- no prefix configured.

Waiting for pull request with proper commit message, thanks

**Comment by alllexx88** [comment]
One more thing: you forgot to add the checksum `checksums/poco-1.7.4.tar.gz.sha512` to the commit

**Comment by murahtin** [comment]
Ok. Fixes : DESTDIR = $ (STAGING_DIR) $ (TARGET_PREFIX).

**Pull request closed without merging**
