### PR TITLE
gphoto2 2.5.8 => 2.5.15, libgphoto2 2.5.8 => 2.5.16

### PR DESCRIPTION
**Pull request by robocoder**
ping @h4de5

### CODE REVIEW

**Comment by h4de5** [comment]
thanks! will try it out soon. how did you know i was searching for this?

**Comment by alllexx88** [comment]
Thanks, merged

**Comment by robocoder** [comment]
@h4de5 I ran across your package request on entware while I was researching a build fix for a different package.

**Comment by h4de5** [comment]
@robocoder : i just tried it - it seems this version has significant less supported cameras, than a previous version, which i installed via apt-get on a WSL.

**on my Synology NAS:**


```
$ /opt/bin/gphoto2 --version

gphoto2 2.5.15
Copyright (c) 2000-2017 Lutz Mueller and others
This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.15         /home/jenkins/Optware-ng/buildroot-i686/toolchain/buildroot-2017.08/output/host/bin/i686-buildroot-linux-gnu-gcc, popt(m), no exif, no cdk, no aa, no jpeg, readline
libgphoto2      2.5.16         all camlibs, /home/jenkins/Optware-ng/buildroot-i686/toolchain/buildroot-2017.08/output/host/bin/i686-buildroot-linux-gnu-gcc, ltdl, no EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb usbdiskdirect usbscsi, /home/jenkins/Optware-ng/buildroot-i686/toolchain/buildroot-2017.08/output/host/bin/i686-buildroot-linux-gnu-gcc, ltdl, USB, serial without locking

```
`$ /opt/bin/gphoto2 --list-cameras  | grep -i sony | wc -l`
**5**

**on WSL:**
```
$ /opt/bin/gphoto2 --version
gphoto2 2.5.9
Copyright (C) 2000-2015 Lutz Mueller and others
This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.9          gcc, popt(m), exif, no cdk, aa, jpeg, readline
libgphoto2      2.5.9          all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         gcc, ltdl, no USB, serial without locking
```

`$ gphoto2 --list-cameras  | grep -i sony | wc -l`
**303**


at this point I doubt this is related to the version, but rather to the OS on my NAS. 

Thank you for the update non the less - I will try to get support from gphoto now.

**Pull request merged**
