### PR TITLE
php 5.6.31 => 5.6.33 (security update)

### PR DESCRIPTION
**Pull request by robocoder**

### CODE REVIEW

**Comment by alllexx88** [comment]
Thanks. Please also reset ipk versions of `php-apache` and `php-opcache` packages (their versions are binded to `php` version)

**Comment by robocoder** [comment]
Thanks. Reset.

**Comment by alllexx88** [comment]
@robocoder 1e307e4d7c0dfb9fb62b1e2c19dad238dfb6416d is not quite what I meant 😃 We don't reset ipk versions of dependent packages upon upgrade. `php-apache` and `php-opcache` are "special case" packages, since their version matches `php` version, and they're compiled from `php` sources:
https://github.com/Optware/Optware-ng/blob/033e61c40456081888262e5e1d6f540bd9467a48/make/php-apache.mk#L24
https://github.com/Optware/Optware-ng/blob/033e61c40456081888262e5e1d6f540bd9467a48/make/php-opcache.mk#L21
`eaccelerator` and `php-thttpd`, on contrary, aren't "special case" packages in the above terms, so they should be left untouched

**Comment by robocoder** [comment]
Fixed. Thanks.

**Comment by alllexx88** [comment]
Thanks. Merged

**Pull request merged**
