### PR TITLE
openssh: 6.7p1-3 => 7.5p1

### PR DESCRIPTION
**Pull request by rivy**
fix ~ [i686] broken `ssh-keygen` and `sshd`

### CODE REVIEW

**Comment by rivy** [comment]
I'm unfortunately some-what naive about building this project. But I was having segfaults with the included "openssh" version (6.7p1-3). So, I spun up a build machine, set it spinning, and modified it to have a "working" version of "openssh".

It's a minor change... only pointing to a more recent version version which is working for Entware-ng, and adding the checksum. No patches were added or changed.

I say "working" because I'm not sure how to test it. So, it's only certified as "currently appears to work on my machine". Hopefully, your Jenkins builder will point out any real problems.

**Comment by alllexx88** [comment]
Hi. Thank you for your contribution! Please also set `OPENSSH_IPK_VERSION=1` in the makefile, and I'll accept this PR.

**Comment by rivy** [comment]
Done!

**Comment by alllexx88** [comment]
Thanks! Merged

**Pull request merged**
