### PR TITLE
minidlna 1.1.5 => 1.2.1

### PR DESCRIPTION
**Pull request by robocoder**
This is a placeholder PR for review/feedback. (I hope to test the ppc603e build tonight.)

* updated the upstream package to 1.2.1 and just enough to get a clean build
* removed the variant minidlna-rescan package
* removed obsolete patches (except `sources/minidlna/inotify-syscalls-mips.patch` ... does mips still need that?)

### CODE REVIEW

**Comment by alllexx88** [comment]
`sources/minidlna/inotify-syscalls-mips.patch` can be safely removed: it was being used back in 2009

**Comment by robocoder** [comment]
I'm still testing this build. Spent the last couple of nights tweaking permissions, /opt/etc/minidlna.conf, /etc/default/minidlna, and /etc/init.d/minidlna on my target machine, a MyBookLive. 

Things on my list to investigate/troubleshoot:
* minidlna complaining about media_dir permissions at startup; to get past this, I made them world rwx but will have to go back and revisit 
* when album art is extracted from a file and copied to the art_cache, minidlna tries to create a symlink to itself (which fails)
* noticeable lag when stopping the minidlna daemon, or coincindentally?, when logging out from ssh session
* unique to my network setup: a upnp control point that handles the server and renderer on different subnets

**Comment by alllexx88** [comment]
I'm interested in this, thank you for your effort, @robocoder

**Comment by robocoder** [comment]
Sorry, I'm abandoning work on this PR. I may revisit it when I redo my network setup...

**Pull request closed without merging**
