### PR TITLE
add ruby-2.3.1 rubygems-2.6.5 cyrus-sasl-2.1.26

### PR DESCRIPTION
**Pull request by Johnsik**

### CODE REVIEW

**Comment by alllexx88** [comment]
Looks good, except the rc script, which was bad originally. Please make it similar to [this one](https://github.com/Optware/Optware-ng/blob/master/sources/freeradius/rc.freeradius) (except the `if [ ! -d %OPTWARE_TARGET_PREFIX%/var/log/radius ]` part, which isn't needed here), replace `psmisc` with `busybox-base` in CYRUS-SASL_DEPENDS, and I'll be glad to accept this.

**Comment by Johnsik** [comment]
Output when install package with new script:
```
[~] # ipkg install /share/CACHEDEV2_DATA/Download/nas_progs/ipk/cyrus-sasl_2.1.26-1_i686.ipk
Installing cyrus-sasl (2.1.26-1) on /opt/.
Configuring cyrus-sasl.

Please read the man page of saslauthd and
check settings in /opt/etc/init.d/S52saslauthd

If you dislike the link /usr/lib/sasl2 -> /opt/lib/sasl2
then you may want to set SASL_PATH instead

Usage: /opt/etc/init.d/S52saslauthd {start|stop|restart|check}
Collected errors:
 * pkg_run_script: package "cyrus-sasl" postinst script returned status 1.
 * opkg_configure: cyrus-sasl.postinst returned 1.
```
It's look like someone call script without `start`

**Comment by alllexx88** [comment]
Right, good that you've noticed this. The sources/cyrus-sasl/postinst script (https://github.com/Optware/Optware-ng/blob/master/sources/cyrus-sasl/postinst) has to be edited to run the rc script with `start`, and prerm (https://github.com/Optware/Optware-ng/blob/master/sources/cyrus-sasl/prerm) -- to run it with `stop` instead of the killall command

**Comment by Johnsik** [comment]
`/opt/etc/init.d/S52saslauthd: line 10: /opt/bin/busybox: No such file or directory`

**Comment by alllexx88** [comment]
Thank you for your contribution! Merging

**Comment by Johnsik** [comment]
There is problem :(
When I try to install ruby gems with native extension compilaton failed.
```
"/home/jenkins/Optware-ng/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.3.0/bin/i686-buildroot-linux-gnu-gcc -o conftest -I/opt/include/ruby-2.3.0/i686-linux-gnu -I/opt/include/ruby-2.3.0/ruby/backward -I/opt/include/ruby-2.3.0 -I. -O2   -pipe -I/home/jenkins/Optware-ng/buildroot-i686/staging/opt/include  -I/home/jenkins/Optware-ng/buildroot-i686/staging/opt/include -D_FILE_OFFSET_BITS=64   -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wno-maybe-uninitialized  -fPIC  conftest.c  -L. -L/opt/lib -Wl,-R/opt/lib -L/home/jenkins/Optware-ng/buildroot-i686/staging/opt/lib -Wl,-R/home/jenkins/Optware-ng/buildroot-i686/staging/opt/lib -L. -Wl,--dynamic-linker=/opt/lib/ld-linux.so.2 -Wl,-rpath,/opt/lib -Wl,-rpath-link,/home/jenkins/Optware-ng/buildroot-i686/staging/opt/lib  -fstack-protector -L/home/jenkins/Optware-ng/buildroot-i686/staging/opt/lib -rdynamic -Wl,-export-dynamic -L/home/jenkins/Optware-ng/buildroot-i686/staging/opt/lib  -Wl,-R/home/jenkins/Optware-ng/buildroot-i686/staging/opt/lib     -Wl,-R/opt/lib -lruby  -lpthread -lgmp -ldl -lcrypt -lm   -lc "

checking if the C compiler accepts ... *** extconf.rb failed ***
```

**Comment by alllexx88** [comment]
@Johnsik I've pushed an untested fix for this recently, and it's already on the feed for the i686 target. Please upgrade and test

**Comment by alllexx88** [comment]
P.S. Of course, you need `gcc` package to be installed for this

**Comment by Johnsik** [comment]
Of course `gcc` is installed. It's isn't problem of ruby package? I'm try to find text `jenkins` inside of it. Nothing...
I'm solve the problem for now to set symlinks for `/home/jenkins/Optware-ng/buildroot-i686/toolchain/buildroot-i686-linux-3.2.66-glibc-5.3.0` and `/home/jenkins/Optware-ng/buildroot-i686/staging/opt` to `/opt`. All extension is compelled. :)

**Comment by alllexx88** [comment]
You shouldn't need those symlinks now: I've patched rbconfig.rb to use correct paths: see ef139876c6d3582ab9c11199d5318da78bf390e6 and 5a505d8484332da7abb83f31421d928c3275944f

**Comment by Johnsik** [comment]
Greate! I't work!

**Pull request merged**
